# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :distribute do
      sh("flutter clean")
      sh("flutter build apk --release")

      release = firebase_app_distribution(
        app: "1:752009926548:android:c757cac8210f029623a181",
        firebase_cli_token: ENV["firebaseCliToken"],
        android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
        testers: "dominic.nguyen.gos@gmail.com",
        release_notes: "First deploy"
      )
  end


  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a beta version to the Google Play"
  lane :beta do
    
    gradle(
    task: 'assemble',
    build_type: 'Release'
  ) 
  latest_release = firebase_app_distribution_get_latest_release(
      app: "1:752009926548:android:c757cac8210f029623a181"
    )
    version_code = latest_release[:buildVersion]
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    sh("flutter clean")
    sh("flutter build appbundle --build-name 1.0.2 --build-number 2 --release")

    upload_to_play_store(
      track: 'internal', 
      release_status: 'draft',
      aab: "../build/app/outputs/bundle/release/app-release.aab",
    )
  end
end
